main.py
from routes.routes import app


if __name__== '__main__':
  app.run(debug=True)

routes/api_route.py
from flask import Blueprint, jsonify, request

from database.database import Book, db


api_route=Blueprint('api_route',__name__,url_prefix="/api/v1" )

@api_route.route('/books/<int:id>',methods=['GET','PUT','DELETE'])

def book_rud(id: int):
    book = Book.query.get_or_404(id)

    if request.method == 'GET':
        return jsonify(book.json()) 
    elif request.method == 'PUT':
        data = request.json
        book.title = data.get('title', book.title)
        book.author = data.get('author', book.author)
        book.published_date = data.get('published_date', book.published_date)
        db.session.commit()
        return jsonify(book.json()), 200
    elif request.method == 'DELETE':
        db.session.delete(book)
        db.session.commit()
        return jsonify({'message': 'Book deleted successfully'}), 204

@api_route.route('/create_book', methods=['POST'])
def create_book():
    data = request.json
    new_book = Book(
        title=data['title'],
        author=data['author'],
        description=data['description'],
        genre_id=data['genre_id']
    )
    db.session.add(new_book)
    db.session.commit()
    return jsonify(new_book.to_dict()), 201

@api_route.route('toggle_read/<int:id>',methods=['PUT'])
def toggle_read(id: int):
    print('Toggle')
    book = Book.query.get_or_404(id)
    book.is_read = request.json.get
    db.session.commit()
    return jsonify({'message': 'Book read status toggled'}), 200

 

routes/api_ruote.py
from flask import Blueprint, jsonify, request

from database.database import Book, db


api_route=Blueprint('api_route',__name__,url_prefix="/api/v1" )

@api_route.route('/books/<int:id>',methods=['GET','PUT','DELETE'])

def book_rud(id: int):
    book = Book.query.get_or_404(id)

    if request.method == 'GET':
        return jsonify(book.json()) 
    elif request.method == 'PUT':
        data = request.json
        book.title = data.get('title', book.title)
        book.author = data.get('author', book.author)
        book.published_date = data.get('published_date', book.published_date)
        db.session.commit()
        return jsonify(book.json()), 200
    elif request.method == 'DELETE':
        db.session.delete(book)
        db.session.commit()
        return jsonify({'message': 'Book deleted successfully'}), 204

@api_route.route('/create_book', methods=['POST'])
def create_book():
    data = request.json
    new_book = Book(
        title=data['title'],
        author=data['author'],
        description=data['description']
        genre_id=data['genre_id']
    )
    db.session.add(new_book)
    db.session.commit()
    return jsonify(new_book.to_dict()), 201
  

routes/routes.py
from flask import Flask
from database.database import  db
from routes.api_route import api_route
from routes.user_route import user_route


app=Flask(__name__,static_folder='../static',template_folder='../templates')

app.config.from_object('config.Config')
db.init_app(app)

with app.app_context():
  db.create_all()

app.register_blueprint(user_route)
app.register_blueprint(api_route)

routes/user_route.py
import os
from flask import Blueprint, flash, redirect, render_template, request, url_for
from sqlalchemy import desc, func
from werkzeug.utils import secure_filename
from config  import Config

from database.database import Book, Genre,db

UPLOAD_FOLDER=Config.UPLOAD_FOLDER
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

def check_filename(filename):
  print(filename)
  return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def secure_file(filename):
  return secure_filename(filename)


def file_saver(request)->str:
  filename=''
  if 'image' in request.files:
    print(f"got image")
    file = request.files['image']
    if file and check_filename(file.filename):
      print(f"Uploading file: {file.filename}")
      filename=secure_file(file.filename)
      file_path = os.path.join(UPLOAD_FOLDER, filename)
        
      print(f"Attempting to save file to: {file_path}")
      try:
        file.save(file_path)
        print(f"File saved to: {file_path}")
      except Exception as e:
        flash(f'An error occurred while saving the file: {str(e)}', 'danger')
        return redirect(request.url)
    else:
        flash('Invalid file', 'danger')
        return redirect(request.url)
  return  filename

  


user_route=Blueprint('user_route',__name__)#,template_folder='../templates', static_folder='../static' )

@user_route.route("/")
def index():
  books = Book.query.order_by(desc(Book.id)).limit(15).all()
  return render_template('index.html', books=books)

@user_route.route('/Books')
def get_books():
  books = Book.query.all()
  return render_template('Books.html', books=books,active_page='books')

@user_route.route('/Genres')
def get_genres():
#   genres = db.session.query(
#     Genre.id,
#     Genre.name,
#     func.count(Book.id).label('book_count') 
# ).outerjoin(Book).group_by(Genre.id, Genre.name).all()
  genres=Genre.query.all()
  return render_template('Genres.html', genres=genres,active_page='genres')


@user_route.route('/Books/create',methods=['GET','POST'])
def create_book():
  if request.method == 'POST':
    file_name=file_saver(request)
    title = request.form.get('title')
    author = request.form.get('author')
    description=request.form.get('description')
    genre_id = request.form.get('genre')
    img_url=url_for('static', filename='uploads/' + file_name)
    
    new_book=Book(
      title=title,
      author=author,
      description=description,
      genre_id=genre_id,
      img_url=img_url
      )

    db.session.add(new_book)
    try:
      db.session.commit()
    except Exception as e:
      db.session.rollback()
      flash('An error occurred while saving to the database.', 'danger')
      return redirect(request.url)
    
    flash('New book created!','success')
    return  redirect(url_for('user_route.get_books'))
  genres=Genre.query.all()
  return  render_template('Books.html',genres=genres,active_page='books',flag='create',method='POST')

@user_route.route('/Books/edit/<int:id>',methods=['GET','POST'])
def edit_book(id):
  book=Book.query.get(id)
  if book is None:
    flash('Book not found', 'danger')
    return redirect(url_for('user_route.get_books'))  
  print(book.id)
  print(request.method)
  if request.method=='POST':
    print(request)
    if request.files['image']:
      file_name=file_saver(request)
      img_url=url_for('static', filename=('uploads/' + file_name))
      book.img_url=img_url
    book.title = request.form.get('title')
    book.author = request.form.get('author')
    book.description=request.form.get('description')
    book.genre_id = request.form.get('genre')
    
    db.session.commit()
    return redirect(url_for('user_route.index')) 
  
  
  
  genres=Genre.query.all()
  return render_template('Books.html',genres=genres, book=book, active_page='books',flag='edit', method='PUT')


@user_route.route('/Genres/create',methods=['GET','POST'])
def create_genre():
  if request.method == 'POST':
    name = request.form.get('name')
    description=request.form.get('description')
    new_book=Genre(
      name=name,
      description=description
      )
    db.session.add(new_book)
    db.session.commit()
    
    flash('New genre created!','success')
    return  redirect(url_for('user_route.get_genres'))
  genres=Genre.query.all()
  return  render_template('Genres.html',active_page='genres',flag='create')
    

templates/Books.html
{% extends "components/base.html" %}

{% block content %}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    <div class="alert alert-dismissible fade show" role="alert">
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}
{% endwith %}
<div class="row m-2">

  {% if flag=='create' or flag=='edit' %}
  <div class="container">

    <div class="row">
      <h3 class="col-sm-1-12  p-2 mb-4 shadow-sm">{{flag}} book record</h3>
    </div>
  {% include "components/create_book.html" %}
    </div>
{% else%}
<a name="create_book" id="create_book" class="btn btn-secondary" href="/Books/create" role="button"> <i class="fa fa-plus-circle fa-lg " aria-hidden="true"> </i>  Create new</a>

</div>
{% include 'components/books_table.html'%}


{% endif %}
  


{%  endblock %}

templates/Genres.html
{% extends "components/base.html" %}

{% block content %}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    <div class="alert alert-dismissible fade show" role="alert">
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}
{% endwith %}
<div class="row m-2">
  {% if flag=='create' %}
  {% include "components/create_genre.html" %}
{% else%}
<a name="create_genre" id="create_genre" class="btn btn-secondary" href="/Genres/create" role="button"> <i class="fa fa-plus-circle fa-lg " aria-hidden="true"> </i>  Create new</a>
</div>
{% if genres %}
<div class="container">
{% include 'components/genre_view.html'%}
</div>
{% endif %}


{% endif %}
  


{%  endblock %}

templates/components/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href={{url_for('static',filename='css/style.css')}}>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" type="text/css">
  
  <script src="https://kit.fontawesome.com/d3cb71fee2.js" crossorigin="anonymous"></script>



  <title>{% block title  %}{% endblock title  %}</title>
</head>
<body>
  {% include "components/header.html" %}
<!--<div class="container"> -->
  {%  block content %}{% endblock content %}
 <!--</div>-->

{% include  "components/footer.html" %}

<script>
  function toggleRead(bookId) {
    console.log('buttotn')
      
          fetch(`/api/v1/toggle_read/${bookId}`, {
              method: 'PUT',
              headers: {
                  'Content-Type': 'application/json',
                  // Add any necessary authentication headers here
              }

          })
          .then(response => {
              if (response.ok) {
                  alert("Read mark saved.");
                  // Optionally, redirect or refresh the page
                  window.location.href = "/"; 
              } else {
                  alert("Failed to save the read mark. Please try again.");
              }
          })
          .catch(error => {
              console.error("Error:", error);
              alert("An error occurred while trying to update the book.");
          });
      
  }
</script>
<script>
  function previewImage(event) {
      const file = event.target.files[0]; 
      const reader = new FileReader(); 
  
      reader.onload = function() {
          const imagePreview = document.getElementById('imagePreview'); 
          imagePreview.src = reader.result; 
          imagePreview.style.display = 'block';
      };
  
      if (file) {
          reader.readAsDataURL(file); 
      }
  }
  </script>
  <script>
      function deleteBook(bookId) {
          if (confirm("Are you sure you want to delete this book?")) {
              fetch(`/api/v1/books/${bookId}`, {
                  method: 'DELETE',
                  headers: {
                      'Content-Type': 'application/json',
                      // Add any necessary authentication headers here
                  }
              })
              .then(response => {
                  if (response.ok) {
                      alert("Book deleted successfully.");
                      // Optionally, redirect or refresh the page
                      window.location.href = "/"; 
                  } else {
                      alert("Failed to delete the book. Please try again.");
                  }
              })
              .catch(error => {
                  console.error("Error:", error);
                  alert("An error occurred while trying to delete the book.");
              });
          }
      }
  </script>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/components/book_view.html
<div class="card  justify-content-between shadow col-lg-3 m-2">

    <div class="card-body">
      <div class="mb-1 row justify-content-around">
         <a href="/Genres#section{{ book.genre_id }}ContentId"> <span class="badge badge-info mb-2 mw">{{ book.genre.name }}</span></a>
        <div>
          <label for="{{book.id}}_is_read">Is read:</label>
          <input type="checkbox" name="is_read" id="{{book.id}}_is_read" {% if book.is_read %}checked{% endif %} onclick="document.getElementById('{{book.id}}_save_btn').disabled = !document.getElementById('{{book.id}}_save_btn').disabled;">
        </div>
      </div>
      <h4 class="card-title text-center shadow bg-primary rounded text-white pr-4 pl-4 p-2">{{ book.title }}</h4>
      <h5 class="card-subtitle text-muted text-center">By {{ book.author }}</h5>
      <img src="{{book.img_url}}" alt="{{ book.title }}" class="bg-light img-fluid w-75 ">
    </div>
    
 <!--    <div class="card-body"> -->
      <p class="card-text bg-light flex-grow-1 text-info m-3">{{ book.description }}</p>
      <div class="row justify-content-around m-1 mb-3 ">   
        <a type="button" href="/Books/edit/{{ book.id }}" class="btn btn-primary">Edit</a>
        <button type="submit" class="btn btn-primary" id="{{book.id}}_save_btn" disabled onclick="toggleRead({{ book.id }})" >Save</button>
      </div>

</div>

templates/components/book_view_compact.html
<div class="card">
  <div class="card-header">
    <div class="row">
    <h6 class="card-title"> <span class="font-weight-bold"> "{{ book.title }}"</span> by {{ book.author }}</h6>
  </div>
</div>

templates/components/books_table.html
<table class="table table-responsive  m-4 ">
  <thead class="thead-inverse">
    <tr class="bg-primary">
      <th>Id</th>
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Image</th>
      <th>Description</th>
      <th>Is read</th>
    </tr>
    </thead>
    <tbody>
{% for book in books %}
<tr >

  <td> {{ book.id }} </td>
  <td> {{ book.title }} </td> 
  <td> {{ book.author }} </td> 
  <td>
    <div class="mb-1 row justify-content-around">
    <a href="/Genres#section{{ book.genre_id }}ContentId"> <span class="badge badge-info mb-2 mw">{{ book.genre.name }}</span></a>
   <div> 

   </td> 
  <td> <img src="{{ book.img_url }}" class=" sm-img img-thumbnail " alt="{{ book.title }} image"> </td> 
  <td> {{ book.description }} </td>
  <td> {{ book.is_read }} </td> 
</tr>
{% endfor %}
    </tbody>
</table>
<style>
  .table tbody tr:hover {
      background: #B6BFEBFF;
      transition: 1s
  }
  .sm-img {
    height:150px
  }
  </style>

templates/components/create_book.html
<!--TODO: split code  into create and edit templates-->
  <form method="POST" action="{% if book %}/Books/edit/{{ book.id }}{% else %} {{ url_for('user_route.create_book') }}{%endif%}"  enctype="multipart/form-data">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" name="title" required value="{% if book %}{{  book.title }}{% endif %}" >
    </div>
    <div class="form-group">
        <label for="author">Author</label>
        <input type="text" class="form-control" id="author" name="author" value="{% if book %}{{ book.author }}{% endif %}" required>
    </div>
    <div class="form-group">
        <label for="image">Image</label>
        <input type="file" class="form-control" id="image" name="image" accept="image/*" onchange="previewImage(event)" >
        <img id="imagePreview" class="img-thumbnail" height="150" width="200" src="{% if book %}{{ book.img_url }}{% endif %}" alt="Image Preview" style=" {% if flag=='create' %}display:none;{% endif %}  margin-top: 10px; max-width: 100%; height: auto;">
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" name="description">{% if book %}{{ book.description }}{% endif %}</textarea>
    </div>
    <div class="form-group">
        <label for="genre_id">Genre ID</label>
      
       <select class="form-select" id="genre" name="genre" value="{% if book %}{{ book.genre_id }}{% endif %}" >
        <option value="" disabled selected={{ flag=='create'}}>Select genre</option>
        {% for genre in genres %}
        <option value="{{ genre.id }}"{% if book %} {% if book.genre_id == genre.id %}selected{% endif %}{% endif %}>{{ genre.name }}</option>

        {% endfor %}

    </select>
    </div>
    <button type="submit" class="btn btn-primary">Save Book</button>
    {% if flag=='edit' %}
    <button type="button" class="btn btn-danger" onclick="deleteBook({{ book.id }})">Delete Book</button>
    {% endif %}
    <button type="button" class="btn btn-secondary" onclick="window.history.back()">Cancel</button>
</form>

templates/components/create_genre.html
<div class="container">

  <div class="row">
    <h3 class="col-sm-1-12  p-2 mb-4 shadow-sm">Create new genre record</h3>
  </div>

  <form method="POST" action="{{ url_for('user_route.create_genre') }}">
    <div class="form-group">
        <label for="name">Genre name</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Enter genre name" required>
    </div>
    <div class="form-group">
      <label for="description">Description</label>
      <textarea class="form-control" id="description" name="description"></textarea>
  </div>
    <button type="submit" class="btn btn-primary">Create Genre</button>
    <button type="button" class="btn btn-secondary" onclick="window.history.back()">Cancel</button>
</form>

</div>

templates/components/genre_view.html
<div id="accordianId" role="tablist" aria-multiselectable="true">
  {% for genre in genres %}
  <div class="card">
    <div class="card-header" role="tab" id="section{{ genre.id }}HeaderId">
      
      <h5 >
        <a data-toggle="collapse" data-parent="#accordianId" href="#section{{ genre.id }}ContentId" aria-expanded="true" aria-controls="section{{ genre.id }}ContentId" class="" >
          {{ genre.name }} 

        </a>
      
        <a name="" id="" class="btn btn-primary float-right " href="#" role="button">Edit</a>
      </h5>
    </div>
    <div id="section1ContentId" class="collapse in" role="tabpanel" aria-labelledby="section{{ genre.id }}HeaderId">
      <div class="card-body">
        <div class="row bg-light  p-3">
        {{ genre.description }}
      </div> 
        <div class="row m-2">
        <div class="container-fluid">
        {% for book in genre.books %}
        {% include 'components/book_view_compact.html' %}
        {% endfor %}
      </div>
    </div>
      </div>
    </div>
  </div>
  {% endfor %}
  <script>
 
    if ( window.location.hash != '' ) {
    openval = window.location.hash.slice(1);
    document.getElementById(openval).className='in collapse show';
    }
    </script>
  

templates/components/header.html
<header>
<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <a class="navbar-brand" href="/"> <i class="fa fa-address-book-o" aria-hidden="true"></i> My Book storage</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation">|||</button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
       <!-- <div class="container"> -->
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item 
            {{ 'active' if active_page=='books' else '' }}
            ">
            
                <a class="nav-link" href="/Books"> <i class="fa fa-book" aria-hidden="true"></i>  Books<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item 
            {{ 'active' if active_page=='genres' else '' }}
            ">
                <a class="nav-link" href="/Genres"> <i class="fas fa-theater-masks    "></i> Genres</a>
            </li>
        </ul>
    </div>
  <!-- </div> -->
</nav>
</header>

templates/index.html
{% extends "components/base.html" %}



{%block title%}
My Book Storage
{% endblock %}

{% block content %}
<div class="row m-4 justify-content-center">
  <h3>Last 15 added books</h3>
</div>


{% if books %}
<div class="container">
<div class="row m-2 ">
  {% for book in books %}
  
  {% include "components/book_view.html" %}
  
  
  
  {% endfor %}
  </div>
</div>
{% endif %}

{% if genres %}

{% endif %}
{%  endblock %}